[build]
functions = "functions"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/api/send-email/"
[[redirects]]
  from = "https://www.ivandorta.netlify.com/*"
  to = "https://www.ivan-dorta.com/:splat"
  status = 301
  force = true