[build]
functions = "functions"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/contact/"
  status = 200
  to = "/.netlify/functions/server/send-email/"